#!/bin/bash

partes=35
archivos="$@"


for i in "$@" ; do
  split $i -n $partes div_
  contador=0
  for j in div* ; do
    if [ $contador -eq 0 ] ; then
      cat < $j > $i
      rm $j
      contador=$(($contador+1))
    else
      rm $j
    fi
    contador=$(($contador+1))  
  done
done

